apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - pgadmin.yaml

secretGenerator:
  - name: jledger-secrets
    behavior: merge
    envs:
      - .env.admin

namePrefix: dev-

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: eureka-server
    spec:
      template:
        spec:
          containers:
            - name: eureka-server
              imagePullPolicy: Never
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: api-gateway
    spec:
      template:
        spec:
          containers:
            - name: api-gateway
              imagePullPolicy: Never
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: core-service
    spec:
      template:
        spec:
          containers:
            - name: core-service
              imagePullPolicy: Never
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: notification-service
    spec:
      template:
        spec:
          containers:
            - name: notification-service
              imagePullPolicy: Never
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: admin-web
    spec:
      template:
        spec:
          containers:
            - name: admin-web
              imagePullPolicy: Never
