# --- EUREKA ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: j-ledger/eureka-server:latest
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  selector:
    app: eureka-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761

# --- API GATEWAY ---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: j-ledger/api-gateway:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: jledger-config
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

# --- CORE SERVICE ---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-service
  template:
    metadata:
      labels:
        app: core-service
    spec:
      containers:
        - name: core-service
          image: j-ledger/core-service:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: jledger-config
          env:
            - name: JLEDGER_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                   name: jledger-secrets
                   key: DB_PASSWORD
            - name: JLEDGER_ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: jledger-secrets
                  key: ADMIN_EMAIL
            - name: JLEDGER_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jledger-secrets
                  key: ADMIN_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: core-service
spec:
  selector:
    app: core-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

# --- NOTIFICATION SERVICE ---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: j-ledger/notification-service:latest
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: jledger-config
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082

# --- ADMIN WEB ---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-web
  template:
    metadata:
      labels:
        app: admin-web
    spec:
      containers:
        - name: admin-web
          image: j-ledger/admin-web:latest
          ports:
            - containerPort: 3000
          env:
            - name: API_GATEWAY_URL
              valueFrom:
                configMapKeyRef:
                  name: jledger-config
                  key: API_GATEWAY_URL
---
apiVersion: v1
kind: Service
metadata:
  name: admin-web
spec:
  selector:
    app: admin-web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

# --- ADMIN API (BFF) ---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-api
  template:
    metadata:
      labels:
        app: admin-api
    spec:
      containers:
        - name: admin-api
          image: j-ledger/admin-api:latest
          ports:
            - containerPort: 3001
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: jledger-config
                  key: ADMIN_API_DATABASE_URL
            - name: JLEDGER_INTERNAL_SECRET
              valueFrom:
                secretKeyRef:
                  name: jledger-secrets
                  key: JLEDGER_INTERNAL_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: admin-api
spec:
  selector:
    app: admin-api
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001

# --- WALLET API (BFF) ---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet-api
  template:
    metadata:
      labels:
        app: wallet-api
    spec:
      containers:
        - name: wallet-api
          image: j-ledger/wallet-api:latest
          ports:
            - containerPort: 3002
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: jledger-config
                  key: WALLET_API_DATABASE_URL
            - name: JLEDGER_INTERNAL_SECRET
              valueFrom:
                secretKeyRef:
                  name: jledger-secrets
                  key: JLEDGER_INTERNAL_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: wallet-api
spec:
  selector:
    app: wallet-api
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
