import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { LedgerProxyService } from '../ledger-proxy/ledger-proxy.service';
import { ScanPayDto } from './dto/scan-pay.dto';
import { v4 as uuidv4 } from 'uuid';

@Injectable()
export class MerchantService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly ledgerProxy: LedgerProxyService,
  ) {}

  async processScanPay(userId: string, accountId: string, dto: ScanPayDto) {
    // 1. Find Merchant by QR Code
    const merchant = await this.prisma.merchantProfile.findUnique({
      where: { qrCodeData: dto.qrCodeData },
    });

    if (!merchant) {
      throw new NotFoundException('Merchant not found for this QR code');
    }

    // 2. Proxy request to Java Core Atomic API
    // We use a random UUID as Idempotency-Key for this demo 
    // (In production, this should be generated by the client or based on transaction intent)
    const idempotencyKey = uuidv4();

    const response = await this.ledgerProxy.forwardToGateway(
      'post',
      '/api/v1/transactions/merchant-pay',
      {
        fromAccountId: accountId,
        merchantAccountId: merchant.merchantAccountId,
        amount: dto.amount,
        currency: 'THB',
      },
    );

    return {
      success: true,
      transactionId: response.id,
      storeName: merchant.storeName,
      amount: dto.amount,
      pointsAwarded: dto.amount * 0.01,
    };
  }
}
