server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: false
      routes:
        - id: core-service-route
          uri: lb://j-ledger
          predicates:
            - Path=/api/v1/**
          filters:
            - name: CircuitBreaker
              args:
                name: coreServiceCircuitBreaker
                fallbackUri: forward:/fallback/core-service
                statusCodes:
                  - 500

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
