server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${JLEDGER_EUREKA_ZONE:http://jledger-eureka:8761/eureka/}

spring:
  application:
    name: core-service
  
  datasource:
    url: ${JLEDGER_DATASOURCE_URL:jdbc:postgresql://localhost:5432/jledger_db}
    username: ${JLEDGER_DATASOURCE_USERNAME:ledger_admin}
    password: ${JLEDGER_DATASOURCE_PASSWORD:ledger_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: ${JLEDGER_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update # Changed from validate to ensure stability if Flyway is slightly behind entity state during dev  
  flyway:
    enabled: true
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: ${JLEDGER_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  data:
    redis:
      repositories:
        enabled: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

jledger:
  redis:
    address: ${JLEDGER_REDIS_ADDRESS:redis://localhost:6379}
    password: ${JLEDGER_REDIS_PASSWORD:redis_password}
    idempotency-ttl-hours: ${JLEDGER_REDIS_IDEMPOTENCY_TTL_HOURS:24}
  lock:
    wait-seconds: ${JLEDGER_LOCK_WAIT_SECONDS:3}
    lease-seconds: ${JLEDGER_LOCK_LEASE_SECONDS:10}
  outbox:
    topic: ${JLEDGER_OUTBOX_TOPIC:transaction-events}
    fixed-delay-ms: ${JLEDGER_OUTBOX_FIXED_DELAY_MS:2000}
    max-retries: ${JLEDGER_OUTBOX_MAX_RETRIES:5}

logging:
  level:
    org.springframework.orm.jpa: ${JLEDGER_JPA_LOG_LEVEL:INFO}
    org.springframework.transaction: ${JLEDGER_TX_LOG_LEVEL:INFO}
