export enum ErrorCode {
  // Identity & Auth Domain
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_INACTIVE_ACCOUNT = 'AUTH_INACTIVE_ACCOUNT',
  AUTH_PASSWORD_NOT_SET = 'AUTH_PASSWORD_NOT_SET',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_INVALID_PIN = 'AUTH_INVALID_PIN',
  AUTH_PIN_LOCKED = 'AUTH_PIN_LOCKED',
  AUTH_PIN_NOT_SET = 'AUTH_PIN_NOT_SET',
  AUTH_REGISTRATION_INCOMPLETE = 'AUTH_REGISTRATION_INCOMPLETE',
  AUTH_REGISTRATION_ALREADY_COMPLETED = 'AUTH_REGISTRATION_ALREADY_COMPLETED',
  AUTH_USER_ALREADY_REGISTERED = 'AUTH_USER_ALREADY_REGISTERED',
  AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',
  AUTH_OTP_INVALID = 'AUTH_OTP_INVALID',
  AUTH_OTP_EXPIRED = 'AUTH_OTP_EXPIRED',
  AUTH_OTP_ALREADY_VERIFIED = 'AUTH_OTP_ALREADY_VERIFIED',
  AUTH_INVALID_SEQUENCE = 'AUTH_INVALID_SEQUENCE',
  AUTH_PHONE_EXISTS = 'AUTH_PHONE_EXISTS',
  AUTH_EMAIL_UNVERIFIED = 'AUTH_EMAIL_UNVERIFIED',

  // Finance Domain
  FINANCE_INSUFFICIENT_BALANCE = 'FINANCE_INSUFFICIENT_BALANCE',
  FINANCE_LIMIT_EXCEEDED = 'FINANCE_LIMIT_EXCEEDED',
  FINANCE_INVALID_AMOUNT = 'FINANCE_INVALID_AMOUNT',
  FINANCE_INVALID_RECIPIENT = 'FINANCE_INVALID_RECIPIENT',
  FINANCE_WALLET_NOT_FOUND = 'FINANCE_WALLET_NOT_FOUND',
  FINANCE_WALLET_FROZEN = 'FINANCE_WALLET_FROZEN',
  FINANCE_ACCOUNT_NOT_FOUND = 'FINANCE_ACCOUNT_NOT_FOUND',
  FINANCE_SYSTEM_SETTINGS_ERROR = 'FINANCE_SYSTEM_SETTINGS_ERROR',
  FINANCE_SYSTEM_ACCOUNTS_NOT_FOUND = 'FINANCE_SYSTEM_ACCOUNTS_NOT_FOUND',

  // KYC Domain
  KYC_DOCUMENT_INVALID = 'KYC_DOCUMENT_INVALID',
  KYC_PII_DECRYPTION_FAILED = 'KYC_PII_DECRYPTION_FAILED',
  KYC_LIVENESS_FAILED = 'KYC_LIVENESS_FAILED',
  KYC_DOPA_FAILED = 'KYC_DOPA_FAILED',
  KYC_ALREADY_VERIFIED = 'KYC_ALREADY_VERIFIED',
  KYC_REJECTED_PERMANENT = 'KYC_REJECTED_PERMANENT',

  // Merchant Domain
  MERCHANT_NOT_FOUND = 'MERCHANT_NOT_FOUND',
  MERCHANT_TERMINAL_NOT_FOUND = 'MERCHANT_TERMINAL_NOT_FOUND',
  MERCHANT_PARTNER_NOT_FOUND = 'MERCHANT_PARTNER_NOT_FOUND',
  MERCHANT_INVALID_CODE = 'MERCHANT_INVALID_CODE',
  MERCHANT_CODE_EXPIRED = 'MERCHANT_CODE_EXPIRED',
  MERCHANT_CODE_USED = 'MERCHANT_CODE_USED',
  MERCHANT_APPLICATION_NOT_FOUND = 'MERCHANT_APPLICATION_NOT_FOUND',
  MERCHANT_SETTLEMENT_NO_BALANCE = 'MERCHANT_SETTLEMENT_NO_BALANCE',

  // Loyalty & Deals
  LOYALTY_INSUFFICIENT_POINTS = 'LOYALTY_INSUFFICIENT_POINTS',
  LOYALTY_RULE_NOT_FOUND = 'LOYALTY_RULE_NOT_FOUND',
  DEAL_NOT_FOUND = 'DEAL_NOT_FOUND',
  DEAL_OUT_OF_STOCK = 'DEAL_OUT_OF_STOCK',
  DEAL_EXPIRED = 'DEAL_EXPIRED',

  // System & Infrastructure
  SYSTEM_ERROR = 'SYSTEM_ERROR',
  SYSTEM_UNAUTHORIZED = 'SYSTEM_UNAUTHORIZED',
  SYSTEM_FORBIDDEN = 'SYSTEM_FORBIDDEN',
  SYSTEM_NOT_FOUND = 'SYSTEM_NOT_FOUND',
  SYSTEM_VALIDATION_ERROR = 'SYSTEM_VALIDATION_ERROR',
  SYSTEM_RATE_LIMIT_EXCEEDED = 'SYSTEM_RATE_LIMIT_EXCEEDED',
}
