export enum TransactionType {
  TOPUP = 'TOPUP',
  TRANSFER = 'TRANSFER',
  WITHDRAW = 'WITHDRAW',
  PAYMENT = 'PAYMENT',
  REFUND = 'REFUND',
}

export enum TransactionStatus {
  FAILED = 'FAILED',
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum AccountStatus {
  ACTIVE = 'ACTIVE',
  FROZEN = 'FROZEN',
}

export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  RECONCILER = 'RECONCILER',
  SUPPORT_STAFF = 'SUPPORT_STAFF',
  INTERNAL = 'INTERNAL',
  USER = 'USER',
}

export enum AdminRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  COMPLIANCE_OFFICER = 'COMPLIANCE_OFFICER',
  SUPPORT_AGENT = 'SUPPORT_AGENT',
  AUDITOR = 'AUDITOR',
}

export enum Permission {
  // Transaction Monitoring
  VIEW_TRANSACTIONS = 'VIEW_TRANSACTIONS',
  VIEW_TRANSACTION_DETAILS = 'VIEW_TRANSACTION_DETAILS',
  VIEW_LEDGER_ENTRIES = 'VIEW_LEDGER_ENTRIES',

  // AML
  VIEW_SUSPICIOUS_ACTIVITIES = 'VIEW_SUSPICIOUS_ACTIVITIES',
  REVIEW_SUSPICIOUS_ACTIVITIES = 'REVIEW_SUSPICIOUS_ACTIVITIES',
  REPORT_TO_AMLO = 'REPORT_TO_AMLO',

  // Account Management
  VIEW_ACCOUNTS = 'VIEW_ACCOUNTS',
  FREEZE_ACCOUNTS = 'FREEZE_ACCOUNTS',
  UNFREEZE_ACCOUNTS = 'UNFREEZE_ACCOUNTS',
  CLOSE_ACCOUNTS = 'CLOSE_ACCOUNTS',

  // Reconciliation
  VIEW_RECONCILIATION_REPORTS = 'VIEW_RECONCILIATION_REPORTS',
  RUN_RECONCILIATION = 'RUN_RECONCILIATION',

  // User Management
  VIEW_USERS = 'VIEW_USERS',
  CREATE_ADMINS = 'CREATE_ADMINS',
  DELETE_ADMINS = 'DELETE_ADMINS',
  MANAGE_STAFF = 'MANAGE_STAFF',
  RESET_STAFF_PASSWORD = 'RESET_STAFF_PASSWORD',
  DEACTIVATE_STAFF = 'DEACTIVATE_STAFF',
  REACTIVATE_STAFF = 'REACTIVATE_STAFF',
  ASSIGN_STAFF_ROLES = 'ASSIGN_STAFF_ROLES',
  FREEZE_USERS = 'FREEZE_USERS',
  UNFREEZE_USERS = 'UNFREEZE_USERS',

  // Dashboard
  VIEW_DASHBOARD = 'VIEW_DASHBOARD',
  VIEW_STATISTICS = 'VIEW_STATISTICS',

  // Audit
  VIEW_AUDIT_LOGS = 'VIEW_AUDIT_LOGS',

  // System
  MANAGE_SYSTEM_ROLES = 'MANAGE_SYSTEM_ROLES',
  MANAGE_SYSTEM_PERMISSIONS = 'MANAGE_SYSTEM_PERMISSIONS',

  // KYC
  VIEW_KYC = 'VIEW_KYC',
  APPROVE_KYC = 'APPROVE_KYC',
  REJECT_KYC = 'REJECT_KYC',

  // Merchant Management
  VIEW_MERCHANTS = 'VIEW_MERCHANTS',
  VIEW_MERCHANT_APPLICATIONS = 'VIEW_MERCHANT_APPLICATIONS',
  APPROVE_MERCHANTS = 'APPROVE_MERCHANTS',
  MANAGE_MERCHANTS = 'MANAGE_MERCHANTS',

  // Promotions & Deals
  VIEW_DEALS = 'VIEW_DEALS',
  MANAGE_DEALS = 'MANAGE_DEALS',
  VIEW_BANNERS = 'VIEW_BANNERS',
  MANAGE_BANNERS = 'MANAGE_BANNERS',

  // Loyalty System
  VIEW_LOYALTY = 'VIEW_LOYALTY',
  MANAGE_LOYALTY = 'MANAGE_LOYALTY',

  // System Settings & Operations
  VIEW_SYSTEM_SETTINGS = 'VIEW_SYSTEM_SETTINGS',
  MANAGE_SYSTEM_SETTINGS = 'MANAGE_SYSTEM_SETTINGS',
  VIEW_SYSTEM_OUTBOX = 'VIEW_SYSTEM_OUTBOX',
  RETRY_SYSTEM_OUTBOX = 'RETRY_SYSTEM_OUTBOX',
}

export enum LedgerEntryType {
  DEBIT = 'DEBIT',
  CREDIT = 'CREDIT',
}

export enum ReconciliationStatus {
  MATCHED = 'MATCHED',
  DISCREPANCY = 'DISCREPANCY',
  STABLE = 'STABLE',
  FIX_REQUIRED = 'FIX_REQUIRED',
}

export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  VIEW = 'VIEW',
  MERCHANT_PAYMENT = 'MERCHANT_PAYMENT',
  MERCHANT_REDEMPTION = 'MERCHANT_REDEMPTION',
  SETTLEMENT = 'SETTLEMENT',
}

export enum ResourceType {
  TRANSACTION = 'TRANSACTION',
  ACCOUNT = 'ACCOUNT',
  USER = 'USER',
  SUSPICIOUS_ACTIVITY = 'SUSPICIOUS_ACTIVITY',
  RECONCILIATION_REPORT = 'RECONCILIATION_REPORT',
  ADMIN_USER = 'ADMIN_USER',
  MERCHANT = 'MERCHANT',
  TERMINAL = 'TERMINAL',
  PARTNER = 'PARTNER',
  DEAL = 'DEAL',
  BANNER = 'BANNER',
  LOYALTY_RULE = 'LOYALTY_RULE',
  SYSTEM_SETTINGS = 'SYSTEM_SETTINGS',
  SYSTEM_OUTBOX = 'SYSTEM_OUTBOX',
}

export enum SuspiciousActivityStatus {
  PENDING = 'PENDING',
  REVIEWED = 'REVIEWED',
  REPORTED = 'REPORTED',
}

// Auth-related enums
export enum UserStatus {
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  BLOCKED = 'BLOCKED',
  DELETED = 'DELETED',
  REJECTED = 'REJECTED',
}

export enum RegistrationState {
  PENDING = 'PENDING',
  PENDING_OTP = 'PENDING_OTP',
  INITIATED = 'INITIATED',
  OTP_VERIFIED = 'OTP_VERIFIED',
  TC_ACCEPTED = 'TC_ACCEPTED',
  ID_CARD_UPLOADED = 'ID_CARD_UPLOADED',
  ID_CARD_CONFIRMED = 'ID_CARD_CONFIRMED',
  KYC_VERIFIED = 'KYC_VERIFIED',
  PROFILE_COMPLETED = 'PROFILE_COMPLETED',
  PASSWORD_SET = 'PASSWORD_SET',
  CREDENTIALS_SET = 'CREDENTIALS_SET',
  COMPLETED = 'COMPLETED',
}

export enum KYCVerificationStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  NOT_STARTED = 'NOT_STARTED', // Virtual status, not stored in DB
}

export enum AddressType {
  REGISTERED = 'REGISTERED',
  CURRENT = 'CURRENT',
  WORK = 'WORK',
  SHIPPING = 'SHIPPING',
  BILLING = 'BILLING',
}

export enum AddressVerificationSource {
  ID_CARD_OCR = 'ID_CARD_OCR',
  MANUAL = 'MANUAL',
  UTILITY_BILL = 'UTILITY_BILL',
  BANK_STATEMENT = 'BANK_STATEMENT',
}

export enum DeviceTrustLevel {
  UNKNOWN = 'UNKNOWN',
  TRUSTED = 'TRUSTED',
  UNTRUSTED = 'UNTRUSTED',
}

export enum NotificationEventType {
  // Onboarding
  REGISTER_INIT_OTP = 'REGISTER_INIT_OTP',
  REGISTER_OTP_VERIFIED = 'REGISTER_OTP_VERIFIED',
  KYC_SUBMITTED = 'KYC_SUBMITTED',
  REGISTRATION_COMPLETED = 'REGISTRATION_COMPLETED',
  KYC_APPROVED = 'KYC_APPROVED',
  KYC_REJECTED = 'KYC_REJECTED',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILURE = 'LOGIN_FAILURE',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',
  PASSWORD_SET = 'PASSWORD_SET',
  PIN_SETUP = 'PIN_SETUP',
  LOGOUT = 'LOGOUT',
  LOGOUT_ALL = 'LOGOUT_ALL',

  // Finance
  TOPUP = 'TOPUP',
  TRANSFER = 'TRANSFER',
  WITHDRAW = 'WITHDRAW',
  PAYMENT = 'PAYMENT',
  REFUND = 'REFUND',
  BILL_PAYMENT = 'BILL_PAYMENT',
  FINANCE = 'FINANCE',

  // Additional Activity Logs
  PROFILE_UPDATED = 'PROFILE_UPDATED',
  ADDRESS_UPDATED = 'ADDRESS_UPDATED',
  DEVICE_REGISTERED = 'DEVICE_REGISTERED',
  PIN_VERIFIED = 'PIN_VERIFIED',
  PIN_FAILURE = 'PIN_FAILURE',
  ACCOUNT_DELETION_REQUESTED = 'ACCOUNT_DELETION_REQUESTED',
  ACCOUNT_DELETED = 'ACCOUNT_DELETED',
  CONSENT_WITHDRAWN = 'CONSENT_WITHDRAWN',

  // Generic & Marketing
  SECURITY = 'SECURITY',
  KYC_STATUS = 'KYC_STATUS',
  SYSTEM = 'SYSTEM',
  PROMO = 'PROMO',
  OFFER = 'OFFER',
  NEWS = 'NEWS',
  ANNOUNCEMENT = 'ANNOUNCEMENT',

  // Loyalty
  LOYALTY_EARN = 'LOYALTY_EARN',
}

export enum KafkaTopic {
  SECURITY_EVENTS = 'security-events',
  KYC_EVENTS = 'kyc-events',
  FINANCE_EVENTS = 'finance-events',
  FINANCIAL_EVENTS_V1 = 'financial-events-v1',
  TRANSACTION_EVENTS = 'transaction-events',
  NOTIFICATION_EVENTS = 'notification-events',
  LOYALTY_EVENTS = 'loyalty-events',
}

export enum NotificationCategory {
  FINANCE = 'FINANCE',
  SYSTEM = 'SYSTEM',
  PROMO = 'PROMO',
  NEWS = 'NEWS',
}

export enum AppPath {
  HOME = '/',
  PROFILE_SECURITY = '/profile/security',
  PROFILE_INFO = '/profile/information',
  TRANSACTION_DETAIL = '/transaction',
  LOYALTY = '/loyalty',
}
