export enum TransactionType {
  TOPUP = 'TOPUP',
  TRANSFER = 'TRANSFER',
  WITHDRAW = 'WITHDRAW',
  PAYMENT = 'PAYMENT',
  REFUND = 'REFUND',
}

export enum TransactionStatus {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  PENDING = 'PENDING',
}

export enum AccountStatus {
  ACTIVE = 'ACTIVE',
  FROZEN = 'FROZEN',
}

export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  RECONCILER = 'RECONCILER',
  SUPPORT_STAFF = 'SUPPORT_STAFF',
  INTERNAL = 'INTERNAL',
  USER = 'USER',
}

export enum AdminRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  COMPLIANCE_OFFICER = 'COMPLIANCE_OFFICER',
  SUPPORT_AGENT = 'SUPPORT_AGENT',
  AUDITOR = 'AUDITOR',
}

export enum Permission {
  // Transaction Monitoring
  VIEW_TRANSACTIONS = 'VIEW_TRANSACTIONS',
  VIEW_TRANSACTION_DETAILS = 'VIEW_TRANSACTION_DETAILS',
  VIEW_LEDGER_ENTRIES = 'VIEW_LEDGER_ENTRIES',

  // AML
  VIEW_SUSPICIOUS_ACTIVITIES = 'VIEW_SUSPICIOUS_ACTIVITIES',
  REVIEW_SUSPICIOUS_ACTIVITIES = 'REVIEW_SUSPICIOUS_ACTIVITIES',
  REPORT_TO_AMLO = 'REPORT_TO_AMLO',

  // Account Management
  VIEW_ACCOUNTS = 'VIEW_ACCOUNTS',
  FREEZE_ACCOUNTS = 'FREEZE_ACCOUNTS',
  UNFREEZE_ACCOUNTS = 'UNFREEZE_ACCOUNTS',
  CLOSE_ACCOUNTS = 'CLOSE_ACCOUNTS',

  // Reconciliation
  VIEW_RECONCILIATION_REPORTS = 'VIEW_RECONCILIATION_REPORTS',
  RUN_RECONCILIATION = 'RUN_RECONCILIATION',

  // User Management
  VIEW_USERS = 'VIEW_USERS',
  CREATE_ADMINS = 'CREATE_ADMINS',
  DELETE_ADMINS = 'DELETE_ADMINS',
  MANAGE_STAFF = 'MANAGE_STAFF',
  RESET_STAFF_PASSWORD = 'RESET_STAFF_PASSWORD',
  DEACTIVATE_STAFF = 'DEACTIVATE_STAFF',
  REACTIVATE_STAFF = 'REACTIVATE_STAFF',
  ASSIGN_STAFF_ROLES = 'ASSIGN_STAFF_ROLES',
  FREEZE_USERS = 'FREEZE_USERS',
  UNFREEZE_USERS = 'UNFREEZE_USERS',

  // Dashboard
  VIEW_DASHBOARD = 'VIEW_DASHBOARD',
  VIEW_STATISTICS = 'VIEW_STATISTICS',

  // Audit
  VIEW_AUDIT_LOGS = 'VIEW_AUDIT_LOGS',

  // System
  MANAGE_SYSTEM_ROLES = 'MANAGE_SYSTEM_ROLES',
  MANAGE_SYSTEM_PERMISSIONS = 'MANAGE_SYSTEM_PERMISSIONS',

  // KYC
  VIEW_KYC = 'VIEW_KYC',
  APPROVE_KYC = 'APPROVE_KYC',
  REJECT_KYC = 'REJECT_KYC',
}

export enum LedgerEntryType {
  DEBIT = 'DEBIT',
  CREDIT = 'CREDIT',
}

export enum ReconciliationStatus {
  MATCHED = 'MATCHED',
  DISCREPANCY = 'DISCREPANCY',
  STABLE = 'STABLE',
  FIX_REQUIRED = 'FIX_REQUIRED',
}

export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  VIEW = 'VIEW',
}

export enum ResourceType {
  TRANSACTION = 'TRANSACTION',
  ACCOUNT = 'ACCOUNT',
  USER = 'USER',
  SUSPICIOUS_ACTIVITY = 'SUSPICIOUS_ACTIVITY',
  RECONCILIATION_REPORT = 'RECONCILIATION_REPORT',
  ADMIN_USER = 'ADMIN_USER',
}

export enum SuspiciousActivityStatus {
  PENDING = 'PENDING',
  REVIEWED = 'REVIEWED',
  REPORTED = 'REPORTED',
}

// Auth-related enums
export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  BLOCKED = 'BLOCKED',
  DELETED = 'DELETED',
}

export enum RegistrationState {
  PENDING = 'PENDING',
  INITIATED = 'INITIATED',
  VERIFIED = 'VERIFIED',
  PROFILE_COMPLETED = 'PROFILE_COMPLETED',
  PASSWORD_SET = 'PASSWORD_SET',
  PIN_SET = 'PIN_SET',
  COMPLETED = 'COMPLETED',
}

export enum DeviceTrustLevel {
  UNKNOWN = 'UNKNOWN',
  TRUSTED = 'TRUSTED',
  UNTRUSTED = 'UNTRUSTED',
}
