package com.jledger.finance.service.wallet;

import com.jledger.finance.domain.entity.LinkedBankAccount;
import com.jledger.finance.domain.entity.Transaction;
import com.jledger.finance.domain.entity.Wallet;
import com.jledger.finance.domain.enums.TransactionType;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import java.util.Optional;

public interface WalletService {
    Wallet createWallet(String userId, String currency);
    Optional<Wallet> getWallet(String userId);
    Wallet updateBalance(String userId, BigDecimal amount);
    boolean validateTransaction(String userId, BigDecimal amount);
    Wallet deactivateWallet(String userId);
    Map<String, BigDecimal> getTransactionLimits(String userId);
    Wallet activateWallet(String userId);
    Wallet freezeWallet(String userId);
    Wallet unfreezeWallet(String userId);
    List<Transaction> getTopUpHistory(String userId);
    String generateStaticQR(String userId);
    List<Transaction> getTransactions(String userId);
    List<Transaction> getTransactions(String userId, Integer page, Integer size, TransactionType type, LocalDateTime from, LocalDateTime to);
    List<Transaction> getQRHistory(String userId);
    Wallet getWalletById(Long id);
    Wallet adjustBalanceById(Long id, BigDecimal amount, String reason);
    Wallet deactivateWalletById(Long id);
    Wallet activateWalletById(Long id);
    Wallet updateLimits(Long id, BigDecimal dailyLimit, BigDecimal monthlyLimit);
    Transaction topUpBank(String userId, BigDecimal amount, Long bankAccountId);
    Transaction creditTopUpFromExternal(String userId, BigDecimal amount, String currency, String externalRef, String provider, String metadataJson);
    List<LinkedBankAccount> listLinkedBankAccounts(String userId);
    LinkedBankAccount createLinkedBankAccount(String userId, String bankCode, String bankName, String accountNumber, String accountName, String accountType, boolean isDefault, boolean isVerified);
    LinkedBankAccount findOwnedLinkedBankAccount(String userId, Long bankAccountId);
    LinkedBankAccount setDefaultLinkedBankAccount(String userId, Long bankAccountId);
    void deleteOwnedLinkedBankAccount(String userId, Long bankAccountId);
    Transaction topUpCounter(String userId, BigDecimal amount, String counterCode);
    Transaction topUpCash(String userId, BigDecimal amount, String agentId);
    Transaction transferByPhone(String fromUserId, String toPhone, BigDecimal amount);
    Map<String, Object> previewTransferByPhone(String fromUserId, String recipientPhone, BigDecimal amount);
    Transaction transferByPhoneV1(String fromUserId, String recipientPhone, BigDecimal amount, String note, String idempotencyKey, Object metadata);
    Transaction transferByWalletId(String fromUserId, String toWalletId, BigDecimal amount, Object metadata);
    Transaction transferWalletToAccount(String fromUserId, String toAccountId, BigDecimal amount, Object metadata);
    Transaction transferByQR(String fromUserId, String qrData, BigDecimal amount);
    String generateQR(String userId, BigDecimal amount);
    Transaction payQR(String fromUserId, String qrData, BigDecimal amount);
    Transaction payUtilityBill(String userId, String billerCode, String accountNumber, BigDecimal amount);
    Transaction payCreditCardBill(String userId, String cardNumber, BigDecimal amount);
    Transaction payMobileTopup(String userId, String phoneNumber, BigDecimal amount);
    Page<Wallet> getAllWallets(Pageable pageable);
    List<Wallet> getAllWallets();
    List<Wallet> searchWallets(String query);
    List<Transaction> getAllTransactions();
    Wallet adjustBalance(String userId, BigDecimal amount, String reason);
    Optional<Transaction> getTransactionById(String id);
}
