server:
  port: 8082

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: ${JLEDGER_KAFKA_BOOTSTRAP_SERVERS}
  datasource:
    url: ${JLEDGER_DATASOURCE_URL}
    username: ${JLEDGER_DATASOURCE_USERNAME}
    password: ${JLEDGER_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jledger:
  outbox:
    topic: ${JLEDGER_OUTBOX_TOPIC:wallet.transaction.events}

springdoc:
  api-docs:
    path: /v3/api-docs
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    serviceUrl:
      defaultZone: ${JLEDGER_EUREKA_ZONE}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
  health:
    db:
      enabled: true
    kafka:
      enabled: true
