export enum AdminRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  COMPLIANCE_OFFICER = 'COMPLIANCE_OFFICER',
  SUPPORT_AGENT = 'SUPPORT_AGENT',
  AUDITOR = 'AUDITOR',
}

export enum Permission {
  // Transaction Monitoring
  VIEW_TRANSACTIONS = 'VIEW_TRANSACTIONS',
  VIEW_TRANSACTION_DETAILS = 'VIEW_TRANSACTION_DETAILS',
  VIEW_LEDGER_ENTRIES = 'VIEW_LEDGER_ENTRIES',

  // AML
  VIEW_SUSPICIOUS_ACTIVITIES = 'VIEW_SUSPICIOUS_ACTIVITIES',
  REVIEW_SUSPICIOUS_ACTIVITIES = 'REVIEW_SUSPICIOUS_ACTIVITIES',
  REPORT_TO_AMLO = 'REPORT_TO_AMLO',

  // Account Management
  VIEW_ACCOUNTS = 'VIEW_ACCOUNTS',
  FREEZE_ACCOUNTS = 'FREEZE_ACCOUNTS',
  UNFREEZE_ACCOUNTS = 'UNFREEZE_ACCOUNTS',
  CLOSE_ACCOUNTS = 'CLOSE_ACCOUNTS',

  // Reconciliation
  VIEW_RECONCILIATION_REPORTS = 'VIEW_RECONCILIATION_REPORTS',
  RUN_RECONCILIATION = 'RUN_RECONCILIATION',

  // User Management
  VIEW_USERS = 'VIEW_USERS',
  CREATE_ADMINS = 'CREATE_ADMINS',
  DELETE_ADMINS = 'DELETE_ADMINS',
  FREEZE_USERS = 'FREEZE_USERS',
  UNFREEZE_USERS = 'UNFREEZE_USERS',

  // KYC Management
  VIEW_KYC = 'VIEW_KYC',
  APPROVE_KYC = 'APPROVE_KYC',
  VIEW_PII = 'VIEW_PII',

  // Dashboard
  VIEW_DASHBOARD = 'VIEW_DASHBOARD',
  VIEW_STATISTICS = 'VIEW_STATISTICS',

  // Audit
  VIEW_AUDIT_LOGS = 'VIEW_AUDIT_LOGS',
}

// Role-Permission Mapping
export const ROLE_PERMISSIONS: Record<AdminRole, Permission[]> = {
  [AdminRole.SUPER_ADMIN]: Object.values(Permission),
  [AdminRole.COMPLIANCE_OFFICER]: [
    Permission.VIEW_TRANSACTIONS,
    Permission.VIEW_TRANSACTION_DETAILS,
    Permission.VIEW_LEDGER_ENTRIES,
    Permission.VIEW_SUSPICIOUS_ACTIVITIES,
    Permission.REVIEW_SUSPICIOUS_ACTIVITIES,
    Permission.REPORT_TO_AMLO,
    Permission.VIEW_ACCOUNTS,
    Permission.VIEW_USERS,
    Permission.VIEW_DASHBOARD,
    Permission.VIEW_STATISTICS,
  ],
  [AdminRole.SUPPORT_AGENT]: [
    Permission.VIEW_TRANSACTIONS,
    Permission.VIEW_TRANSACTION_DETAILS,
    Permission.VIEW_ACCOUNTS,
    Permission.VIEW_USERS,
    Permission.VIEW_DASHBOARD,
  ],
  [AdminRole.AUDITOR]: [
    Permission.VIEW_TRANSACTIONS,
    Permission.VIEW_TRANSACTION_DETAILS,
    Permission.VIEW_LEDGER_ENTRIES,
    Permission.VIEW_SUSPICIOUS_ACTIVITIES,
    Permission.VIEW_ACCOUNTS,
    Permission.VIEW_RECONCILIATION_REPORTS,
    Permission.VIEW_USERS,
    Permission.VIEW_AUDIT_LOGS,
  ],
};
