apiVersion: v1
kind: ConfigMap
metadata:
  name: jledger-config
data:
  DB_NAME: "jledger_db"
  JLEDGER_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/jledger_db"
  JLEDGER_DATASOURCE_USERNAME: "ledger_admin"
  JLEDGER_REDIS_ADDRESS: "redis://redis-service:6379"
  JLEDGER_KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
  API_GATEWAY_URL: "http://api-gateway:8080"
---
apiVersion: v1
kind: Secret
metadata:
  name: jledger-secrets
type: Opaque
stringData:
  DB_USER: "ledger_admin"
  DB_PASSWORD: "ledger_password"
  REDIS_PASSWORD: "redis_password"
