apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: prod-

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: api-gateway
    spec:
      replicas: 3
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: core-service
    spec:
      replicas: 3
