package com.jledger.core.domain;

public enum SuspiciousActivityType {
    LARGE_TRANSACTION,
    HIGH_FREQUENCY,
    ROUND_NUMBER,
    RAPID_MOVEMENT,
    HIGH_RISK_JURISDICTION,
    MULTIPLE_RECIPIENTS,
    STRUCTURING,
    UNUSUAL_PATTERN,
    RAPID_TRANSFER_ACTIVITY,
    UNUSUAL_TRANSACTION_AMOUNT,
    UNUSUAL_LOCATION,
    MULTIPLE_FAILED_LOGINS,
    UNUSUAL_IP_ADDRESS,
    RAPID_ACCOUNT_CHANGES,
    SENSITIVE_ACCOUNT_CHANGE
}
