import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased dark`}>
      <body className="min-h-full flex bg-[#030712] text-gray-200">
        <aside className="w-64 bg-gray-950 border-r border-gray-900 hidden md:flex flex-col">
          <div className="h-16 flex items-center px-6 border-b border-gray-900">
            <span className="text-xl font-bold bg-gradient-to-r from-blue-400 to-indigo-500 bg-clip-text text-transparent">J-Ledger Admin</span>
          </div>
          <nav className="flex-1 px-4 py-6 space-y-2">
            <a href="/" className="flex items-center px-4 py-3 text-sm font-medium rounded-xl bg-blue-500/10 text-blue-400 hover:bg-blue-500/20 transition-colors">
               Dashboard
            </a>
            <a href="/transactions" className="flex items-center px-4 py-3 text-sm font-medium rounded-xl text-gray-400 hover:bg-gray-900 hover:text-gray-200 transition-colors">
               Transactions
            </a>
          </nav>
          <div className="p-4 border-t border-gray-900">
            <div className="flex items-center gap-3 px-4 py-2">
              <div className="w-8 h-8 rounded-full bg-gradient-to-tr from-indigo-500 to-purple-500"></div>
              <div className="flex flex-col">
                <span className="text-sm font-medium text-white">Admin Profile</span>
                <span className="text-xs text-gray-500">admin@jledger.io</span>
              </div>
            </div>
          </div>
        </aside>
        <main className="flex-1 overflow-auto">
          <div className="h-16 flex items-center px-8 border-b border-gray-900/50 block md:hidden">
            <span className="text-lg font-bold">J-Ledger Menu</span>
          </div>
          <div className="p-8 max-w-7xl mx-auto">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
